-- Dimension tables in RAW schema
-- Co-authored with CoCo

USE DATABASE AEROSPACE_SUPPLY_CHAIN_AI;
USE SCHEMA RAW;

-- ============================================================
-- DIM_RAW_MATERIAL
-- ============================================================
CREATE OR REPLACE TABLE DIM_RAW_MATERIAL (
    RAW_MATERIAL_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    MATERIAL_ID VARCHAR(20) NOT NULL,
    MATERIAL_NAME VARCHAR(100) NOT NULL,
    MATERIAL_GROUP VARCHAR(50),
    UNIT_OF_MEASURE VARCHAR(20),
    STANDARD_COST NUMBER(15,4),
    LEAD_TIME_DAYS NUMBER(5,0),
    SHELF_LIFE_DAYS NUMBER(5,0),
    HAZMAT_CLASS VARCHAR(20),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (MATERIAL_ID),
    PRIMARY KEY (RAW_MATERIAL_SK)
);

-- ============================================================
-- DIM_PART
-- ============================================================
CREATE OR REPLACE TABLE DIM_PART (
    PART_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    PART_ID VARCHAR(20) NOT NULL,
    PART_NAME VARCHAR(200) NOT NULL,
    PART_FAMILY VARCHAR(50),
    ATA_CHAPTER NUMBER(3,0),
    UNIT_COST NUMBER(15,4),
    WEIGHT_KG NUMBER(10,3),
    LEAD_TIME_DAYS NUMBER(5,0),
    SAFETY_STOCK NUMBER(10,0),
    REORDER_POINT NUMBER(10,0),
    MAKE_BUY_CODE VARCHAR(10),
    CRITICALITY VARCHAR(20),
    LIFECYCLE_STATUS VARCHAR(20) DEFAULT 'Active',
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (PART_ID),
    PRIMARY KEY (PART_SK)
);

-- ============================================================
-- DIM_PLANT
-- ============================================================
CREATE OR REPLACE TABLE DIM_PLANT (
    PLANT_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    PLANT_ID VARCHAR(20) NOT NULL,
    PLANT_NAME VARCHAR(200) NOT NULL,
    CITY VARCHAR(100),
    COUNTRY VARCHAR(50),
    REGION VARCHAR(50),
    CAPACITY_UNITS NUMBER(10,0),
    SHIFTS_PER_DAY NUMBER(1,0) DEFAULT 2,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (PLANT_ID),
    PRIMARY KEY (PLANT_SK)
);

-- ============================================================
-- DIM_SUPPLIER
-- ============================================================
CREATE OR REPLACE TABLE DIM_SUPPLIER (
    SUPPLIER_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    SUPPLIER_ID VARCHAR(20) NOT NULL,
    SUPPLIER_NAME VARCHAR(200) NOT NULL,
    COUNTRY VARCHAR(50),
    REGION VARCHAR(50),
    TIER_LEVEL NUMBER(1,0),
    CATEGORY VARCHAR(50),
    RISK_SCORE NUMBER(5,2),
    QUALITY_SCORE NUMBER(5,2),
    DELIVERY_SCORE NUMBER(5,2),
    FINANCIAL_RISK VARCHAR(20),
    CERTIFICATION_STATUS VARCHAR(50),
    ANNUAL_SPEND NUMBER(15,2),
    CONTRACT_END_DATE DATE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (SUPPLIER_ID),
    PRIMARY KEY (SUPPLIER_SK)
);

-- ============================================================
-- DIM_SUPPLIER_PART
-- ============================================================
CREATE OR REPLACE TABLE DIM_SUPPLIER_PART (
    SUPPLIER_PART_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    SUPPLIER_ID VARCHAR(20) NOT NULL,
    PART_ID VARCHAR(20) NOT NULL,
    UNIT_PRICE NUMBER(15,4),
    LEAD_TIME_DAYS NUMBER(5,0),
    MIN_ORDER_QTY NUMBER(10,0),
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE DATE,
    IS_PREFERRED BOOLEAN DEFAULT FALSE,
    QUALIFICATION_STATUS VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SUPPLIER_PART_SK)
);

-- ============================================================
-- DIM_CUSTOMER
-- ============================================================
CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    CUSTOMER_ID VARCHAR(15) NOT NULL,
    CUSTOMER_NAME VARCHAR(200) NOT NULL,
    CUSTOMER_TYPE VARCHAR(50),
    COUNTRY VARCHAR(50),
    REGION VARCHAR(50),
    REVENUE_TIER VARCHAR(20),
    ANNUAL_REVENUE NUMBER(15,2),
    CONTRACT_STATUS VARCHAR(20) DEFAULT 'Active',
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (CUSTOMER_ID),
    PRIMARY KEY (CUSTOMER_SK)
);

-- ============================================================
-- DIM_WAREHOUSE
-- ============================================================
CREATE OR REPLACE TABLE DIM_WAREHOUSE (
    WAREHOUSE_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    WAREHOUSE_ID VARCHAR(20) NOT NULL,
    WAREHOUSE_NAME VARCHAR(200) NOT NULL,
    PLANT_ID VARCHAR(20),
    WAREHOUSE_TYPE VARCHAR(50),
    CAPACITY_SQFT NUMBER(10,0),
    TEMPERATURE_CONTROLLED BOOLEAN DEFAULT FALSE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (WAREHOUSE_ID),
    PRIMARY KEY (WAREHOUSE_SK)
);

-- ============================================================
-- DIM_WORK_CENTER
-- ============================================================
CREATE OR REPLACE TABLE DIM_WORK_CENTER (
    WORK_CENTER_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    WORK_CENTER_ID VARCHAR(20) NOT NULL,
    WORK_CENTER_NAME VARCHAR(200) NOT NULL,
    PLANT_ID VARCHAR(20),
    WORK_CENTER_TYPE VARCHAR(50),
    MACHINE_TYPE VARCHAR(50),
    CAPACITY_HOURS_PER_DAY NUMBER(5,2),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (WORK_CENTER_ID),
    PRIMARY KEY (WORK_CENTER_SK)
);

-- ============================================================
-- DIM_BOM (Bill of Materials)
-- ============================================================
CREATE OR REPLACE TABLE DIM_BOM (
    BOM_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    BOM_ID VARCHAR(20) NOT NULL,
    PARENT_PART_ID VARCHAR(20),
    CHILD_PART_ID VARCHAR(20),
    QUANTITY_PER NUMBER(10,4),
    UNIT_OF_MEASURE VARCHAR(20),
    BOM_LEVEL NUMBER(3,0),
    EFFECTIVE_DATE DATE,
    EXPIRATION_DATE DATE,
    PROGRAM VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (BOM_ID),
    PRIMARY KEY (BOM_SK)
);

-- ============================================================
-- DIM_ROUTING
-- ============================================================
CREATE OR REPLACE TABLE DIM_ROUTING (
    ROUTING_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    ROUTING_ID VARCHAR(20) NOT NULL,
    PART_ID VARCHAR(20),
    OPERATION_SEQ NUMBER(5,0),
    WORK_CENTER_ID VARCHAR(20),
    OPERATION_NAME VARCHAR(100),
    SETUP_TIME_MIN NUMBER(8,2),
    RUN_TIME_MIN NUMBER(8,2),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (ROUTING_ID),
    PRIMARY KEY (ROUTING_SK)
);

-- ============================================================
-- DIM_CARRIER
-- ============================================================
CREATE OR REPLACE TABLE DIM_CARRIER (
    CARRIER_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    CARRIER_ID VARCHAR(20) NOT NULL,
    CARRIER_NAME VARCHAR(200) NOT NULL,
    SERVICE_TYPE VARCHAR(50),
    COVERAGE_REGION VARCHAR(100),
    ON_TIME_RATE NUMBER(5,2),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (CARRIER_ID),
    PRIMARY KEY (CARRIER_SK)
);

-- ============================================================
-- DIM_CERTIFICATION
-- ============================================================
CREATE OR REPLACE TABLE DIM_CERTIFICATION (
    CERTIFICATION_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    CERTIFICATION_ID VARCHAR(20) NOT NULL,
    PART_ID VARCHAR(20),
    SUPPLIER_ID VARCHAR(20),
    CERTIFICATION_TYPE VARCHAR(100),
    CERTIFYING_BODY VARCHAR(100),
    ISSUE_DATE DATE,
    EXPIRY_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'Active',
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (CERTIFICATION_ID),
    PRIMARY KEY (CERTIFICATION_SK)
);

-- ============================================================
-- DIM_CALENDAR
-- ============================================================
CREATE OR REPLACE TABLE DIM_CALENDAR (
    CALENDAR_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    DATE_KEY DATE NOT NULL,
    YEAR NUMBER(4,0),
    QUARTER NUMBER(1,0),
    MONTH NUMBER(2,0),
    MONTH_NAME VARCHAR(20),
    WEEK_OF_YEAR NUMBER(2,0),
    DAY_OF_WEEK NUMBER(1,0),
    DAY_NAME VARCHAR(20),
    IS_WORKING_DAY BOOLEAN,
    FISCAL_YEAR NUMBER(4,0),
    FISCAL_QUARTER NUMBER(1,0),
    UNIQUE (DATE_KEY),
    PRIMARY KEY (CALENDAR_SK)
);
