-- Fact tables in RAW schema
-- Co-authored with CoCo

USE DATABASE AEROSPACE_SUPPLY_CHAIN_AI;
USE SCHEMA RAW;

-- ============================================================
-- FACT_SHIPMENT
-- ============================================================
CREATE OR REPLACE TABLE FACT_SHIPMENT CLUSTER BY LINEAR(SHIP_DATE, SHIPMENT_TYPE) (
    SHIPMENT_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    SHIPMENT_ID VARCHAR(20) NOT NULL,
    SHIPMENT_TYPE VARCHAR(10),
    CARRIER_ID VARCHAR(20),
    ORIGIN_PLANT_ID VARCHAR(20),
    DESTINATION_PLANT_ID VARCHAR(20),
    SUPPLIER_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(15),
    PO_ID VARCHAR(20),
    SO_ID VARCHAR(20),
    SHIP_DATE DATE,
    PROMISED_DELIVERY_DATE DATE,
    ACTUAL_DELIVERY_DATE DATE,
    FREIGHT_COST NUMBER(12,2),
    WEIGHT_KG NUMBER(10,2),
    STATUS VARCHAR(50),
    IS_ON_TIME BOOLEAN,
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (SHIPMENT_ID),
    PRIMARY KEY (SHIPMENT_SK)
);

-- ============================================================
-- FACT_PURCHASE_ORDER
-- ============================================================
CREATE OR REPLACE TABLE FACT_PURCHASE_ORDER CLUSTER BY LINEAR(ORDER_DATE, SUPPLIER_ID) (
    PO_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    PO_ID VARCHAR(20) NOT NULL,
    SUPPLIER_ID VARCHAR(20),
    PLANT_ID VARCHAR(20),
    ORDER_DATE DATE,
    PROMISED_DATE DATE,
    RECEIVED_DATE DATE,
    TOTAL_VALUE NUMBER(15,2),
    CURRENCY VARCHAR(3) DEFAULT 'USD',
    STATUS VARCHAR(50),
    BUYER_ID VARCHAR(20),
    PRIORITY VARCHAR(20),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (PO_ID),
    PRIMARY KEY (PO_SK)
);

-- ============================================================
-- FACT_PURCHASE_ORDER_LINE
-- ============================================================
CREATE OR REPLACE TABLE FACT_PURCHASE_ORDER_LINE (
    PO_LINE_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    PO_LINE_ID VARCHAR(30) NOT NULL,
    PO_ID VARCHAR(20),
    PART_ID VARCHAR(20),
    QUANTITY_ORDERED NUMBER(10,0),
    QUANTITY_RECEIVED NUMBER(10,0),
    UNIT_PRICE NUMBER(15,4),
    LINE_VALUE NUMBER(15,2),
    FREIGHT_COST NUMBER(12,2),
    LANDED_COST NUMBER(15,2),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (PO_LINE_ID),
    PRIMARY KEY (PO_LINE_SK)
);

-- ============================================================
-- FACT_PURCHASE_REQUISITION
-- ============================================================
CREATE OR REPLACE TABLE FACT_PURCHASE_REQUISITION (
    PR_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    PR_ID VARCHAR(20) NOT NULL,
    PART_ID VARCHAR(20),
    PLANT_ID VARCHAR(20),
    REQUESTED_DATE DATE,
    REQUIRED_DATE DATE,
    QUANTITY NUMBER(10,0),
    ESTIMATED_COST NUMBER(15,2),
    STATUS VARCHAR(50),
    REQUESTOR_ID VARCHAR(20),
    PRIORITY VARCHAR(20),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (PR_ID),
    PRIMARY KEY (PR_SK)
);

-- ============================================================
-- FACT_SALES_ORDER
-- ============================================================
CREATE OR REPLACE TABLE FACT_SALES_ORDER CLUSTER BY LINEAR(ORDER_DATE, CUSTOMER_ID) (
    SO_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    SO_ID VARCHAR(20) NOT NULL,
    CUSTOMER_ID VARCHAR(15),
    PLANT_ID VARCHAR(20),
    ORDER_DATE DATE,
    REQUESTED_DATE DATE,
    PROMISED_DATE DATE,
    TOTAL_VALUE NUMBER(15,2),
    CURRENCY VARCHAR(3) DEFAULT 'USD',
    STATUS VARCHAR(50),
    PRIORITY VARCHAR(20),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (SO_ID),
    PRIMARY KEY (SO_SK)
);

-- ============================================================
-- FACT_SALES_ORDER_LINE
-- ============================================================
CREATE OR REPLACE TABLE FACT_SALES_ORDER_LINE (
    SO_LINE_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    SO_LINE_ID VARCHAR(30) NOT NULL,
    SO_ID VARCHAR(20),
    PART_ID VARCHAR(20),
    QUANTITY_ORDERED NUMBER(10,0),
    QUANTITY_SHIPPED NUMBER(10,0),
    UNIT_PRICE NUMBER(15,4),
    LINE_VALUE NUMBER(15,2),
    BACKORDER_QTY NUMBER(10,0) DEFAULT 0,
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (SO_LINE_ID),
    PRIMARY KEY (SO_LINE_SK)
);

-- ============================================================
-- FACT_WORK_ORDER
-- ============================================================
CREATE OR REPLACE TABLE FACT_WORK_ORDER CLUSTER BY LINEAR(ORDER_DATE, PLANT_ID) (
    WO_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    WO_ID VARCHAR(20) NOT NULL,
    PART_ID VARCHAR(20),
    PLANT_ID VARCHAR(20),
    WORK_CENTER_ID VARCHAR(20),
    ORDER_DATE DATE,
    PLANNED_START_DATE DATE,
    ACTUAL_START_DATE DATE,
    PLANNED_END_DATE DATE,
    ACTUAL_END_DATE DATE,
    QUANTITY_PLANNED NUMBER(10,0),
    QUANTITY_PRODUCED NUMBER(10,0),
    QUANTITY_SCRAPPED NUMBER(10,0),
    YIELD_RATE NUMBER(5,2),
    STATUS VARCHAR(50),
    WO_TYPE VARCHAR(50),
    PRIORITY VARCHAR(20),
    PROGRAM VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (WO_ID),
    PRIMARY KEY (WO_SK)
);

-- ============================================================
-- FACT_INVENTORY
-- ============================================================
CREATE OR REPLACE TABLE FACT_INVENTORY CLUSTER BY LINEAR(SNAPSHOT_DATE, PLANT_ID) (
    INVENTORY_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    INVENTORY_ID VARCHAR(20) NOT NULL,
    PART_ID VARCHAR(20),
    PLANT_ID VARCHAR(20),
    WAREHOUSE_ID VARCHAR(20),
    SNAPSHOT_DATE DATE,
    AVAILABLE_QTY NUMBER(10,0),
    RESERVED_QTY NUMBER(10,0),
    ON_HAND_QTY NUMBER(10,0),
    TOTAL_VALUE NUMBER(15,2),
    DAYS_OF_INVENTORY NUMBER(8,2),
    REORDER_POINT NUMBER(10,0),
    SAFETY_STOCK NUMBER(10,0),
    MAX_STOCK_LEVEL NUMBER(10,0),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (INVENTORY_ID),
    PRIMARY KEY (INVENTORY_SK)
);

-- ============================================================
-- FACT_INVENTORY_MOVEMENT
-- ============================================================
CREATE OR REPLACE TABLE FACT_INVENTORY_MOVEMENT (
    MOVEMENT_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    MOVEMENT_ID VARCHAR(20) NOT NULL,
    PART_ID VARCHAR(20),
    PLANT_ID VARCHAR(20),
    WAREHOUSE_ID VARCHAR(20),
    MOVEMENT_DATE DATE,
    MOVEMENT_TYPE VARCHAR(50),
    QUANTITY NUMBER(10,0),
    REFERENCE_ID VARCHAR(30),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (MOVEMENT_ID),
    PRIMARY KEY (MOVEMENT_SK)
);

-- ============================================================
-- FACT_QUALITY_EVENT
-- ============================================================
CREATE OR REPLACE TABLE FACT_QUALITY_EVENT CLUSTER BY LINEAR(EVENT_DATE, PLANT_ID) (
    QE_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    QE_ID VARCHAR(20) NOT NULL,
    PART_ID VARCHAR(20),
    SUPPLIER_ID VARCHAR(20),
    PLANT_ID VARCHAR(20),
    EVENT_DATE DATE,
    EVENT_TYPE VARCHAR(50),
    SEVERITY VARCHAR(20),
    DEFECT_TYPE VARCHAR(100),
    ROOT_CAUSE VARCHAR(200),
    CORRECTIVE_ACTION VARCHAR(200),
    DISPOSITION VARCHAR(50),
    QUANTITY_INSPECTED NUMBER(10,0),
    QUANTITY_DEFECTIVE NUMBER(10,0),
    COST_OF_QUALITY NUMBER(12,2),
    RESOLUTION_DATE DATE,
    STATUS VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (QE_ID),
    PRIMARY KEY (QE_SK)
);

-- ============================================================
-- FACT_REPAIR_ORDER
-- ============================================================
CREATE OR REPLACE TABLE FACT_REPAIR_ORDER (
    REPAIR_ORDER_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    REPAIR_ORDER_ID VARCHAR(20) NOT NULL,
    ENGINE_SN VARCHAR(30),
    PART_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(15),
    RECEIVED_DATE DATE,
    RELEASED_DATE DATE,
    REPAIR_COST NUMBER(15,2),
    REPAIR_STATUS VARCHAR(50),
    TECHNICIAN_ID VARCHAR(20),
    REPAIR_TYPE VARCHAR(50),
    WARRANTY_FLAG VARCHAR(1),
    TURNAROUND_TIME_DAYS NUMBER(5,0),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (REPAIR_ORDER_ID),
    PRIMARY KEY (REPAIR_ORDER_SK)
);

-- ============================================================
-- FACT_IOT_SENSOR_DATA
-- ============================================================
CREATE OR REPLACE TABLE FACT_IOT_SENSOR_DATA CLUSTER BY LINEAR(READING_TIMESTAMP, PLANT_ID) (
    SENSOR_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    SENSOR_ID VARCHAR(20) NOT NULL,
    WORK_CENTER_ID VARCHAR(20),
    PLANT_ID VARCHAR(20),
    READING_TIMESTAMP TIMESTAMP_NTZ(9),
    TEMPERATURE_C NUMBER(8,2),
    VIBRATION_MM_S NUMBER(8,2),
    PRESSURE_BAR NUMBER(8,2),
    RPM NUMBER(10,0),
    POWER_KW NUMBER(8,2),
    OIL_LEVEL_PCT NUMBER(5,2),
    STATUS VARCHAR(20),
    ALERT_FLAG BOOLEAN,
    PRIMARY KEY (SENSOR_SK)
);

-- ============================================================
-- FACT_AOG_EVENT (Aircraft On Ground)
-- ============================================================
CREATE OR REPLACE TABLE FACT_AOG_EVENT (
    AOG_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    AOG_ID VARCHAR(20) NOT NULL,
    CUSTOMER_ID VARCHAR(15),
    PART_ID VARCHAR(20),
    EVENT_DATE DATE,
    DURATION_HOURS NUMBER(8,2),
    REVENUE_IMPACT NUMBER(15,2),
    ROOT_CAUSE VARCHAR(500),
    RESOLUTION_ACTION VARCHAR(500),
    SEVERITY_CODE VARCHAR(20),
    RESOLUTION_DATE DATE,
    MAINTENANCE_PROVIDER_ID VARCHAR(20),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (AOG_ID),
    PRIMARY KEY (AOG_SK)
);
