-- Metadata tables in RAW schema (business glossary and metric definitions)
-- Co-authored with CoCo

USE DATABASE AEROSPACE_SUPPLY_CHAIN_AI;
USE SCHEMA RAW;

-- ============================================================
-- META_BUSINESS_GLOSSARY
-- ============================================================
CREATE OR REPLACE TABLE META_BUSINESS_GLOSSARY (
    TERM_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    TERM_ID VARCHAR(15) NOT NULL,
    BUSINESS_TERM VARCHAR(100) NOT NULL,
    BUSINESS_DEFINITION VARCHAR(500),
    SOURCE_TABLE VARCHAR(100),
    FORMULA VARCHAR(1000),
    OWNER VARCHAR(100),
    STATUS VARCHAR(20) DEFAULT 'Active',
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (TERM_ID),
    PRIMARY KEY (TERM_SK)
);

-- ============================================================
-- META_METRIC_DEFINITION
-- ============================================================
CREATE OR REPLACE TABLE META_METRIC_DEFINITION (
    METRIC_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    METRIC_ID VARCHAR(15) NOT NULL,
    METRIC_NAME VARCHAR(100) NOT NULL,
    METRIC_DESCRIPTION VARCHAR(500),
    FORMULA VARCHAR(2000),
    UNIT VARCHAR(20),
    TARGET_VALUE NUMBER(18,4),
    SOURCE_TABLES VARCHAR(500),
    GRAIN VARCHAR(200),
    BUSINESS_RULE VARCHAR(1000),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (METRIC_ID),
    PRIMARY KEY (METRIC_SK)
);
