-- Analytics schema tables (KPIs and thresholds)
-- Co-authored with CoCo

USE DATABASE AEROSPACE_SUPPLY_CHAIN_AI;
USE SCHEMA ANALYTICS;

-- ============================================================
-- EXECUTIVE_KPI_MONTHLY
-- ============================================================
CREATE OR REPLACE TABLE EXECUTIVE_KPI_MONTHLY (
    KPI_SK NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    YEAR NUMBER(4,0),
    MONTH NUMBER(2,0),
    MONTH_NAME VARCHAR(20),
    QUARTER NUMBER(1,0),
    FISCAL_YEAR NUMBER(4,0),
    FISCAL_QUARTER NUMBER(1,0),
    OTD_PCT NUMBER(8,2),
    FILL_RATE_PCT NUMBER(8,2),
    PROCUREMENT_SPEND NUMBER(18,2),
    AVG_YIELD_RATE NUMBER(8,2),
    SCRAP_RATE NUMBER(8,2),
    DEFECT_RATE NUMBER(8,2),
    TOTAL_COPQ NUMBER(18,2),
    TOTAL_SHIPMENTS NUMBER(10,0),
    TOTAL_REVENUE NUMBER(18,2),
    PO_COUNT NUMBER(10,0),
    WO_COUNT NUMBER(10,0),
    QUALITY_EVENT_COUNT NUMBER(10,0),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (KPI_SK)
);

-- ============================================================
-- METRIC_THRESHOLDS
-- ============================================================
CREATE OR REPLACE TABLE METRIC_THRESHOLDS (
    METRIC_ID VARCHAR(15) NOT NULL,
    METRIC_NAME VARCHAR(100),
    GREEN_MIN NUMBER(18,4),
    GREEN_MAX NUMBER(18,4),
    YELLOW_MIN NUMBER(18,4),
    YELLOW_MAX NUMBER(18,4),
    RED_THRESHOLD NUMBER(18,4),
    DIRECTION VARCHAR(20)
);
