-- Analytics schema views (derived metrics and governance)
-- Co-authored with CoCo

USE DATABASE AEROSPACE_SUPPLY_CHAIN_AI;
USE SCHEMA ANALYTICS;

-- ============================================================
-- V_DERIVED_SUPPLIER_RISK
-- ============================================================
CREATE OR REPLACE VIEW V_DERIVED_SUPPLIER_RISK AS
SELECT
  s.SUPPLIER_ID, s.SUPPLIER_NAME, s.TIER_LEVEL, s.CATEGORY, s.COUNTRY, s.REGION,
  s.RISK_SCORE, s.QUALITY_SCORE, s.DELIVERY_SCORE, s.FINANCIAL_RISK, s.ANNUAL_SPEND,
  ROUND((COALESCE(s.QUALITY_SCORE,0)*0.30) + (COALESCE(s.DELIVERY_SCORE,0)*0.30)
    + (CASE WHEN s.ANNUAL_SPEND > 10000000 THEN 80 ELSE 60 END * 0.20)
    + (75 * 0.20), 2) AS SPI_SCORE,
  CASE WHEN s.DELIVERY_SCORE < 85 OR s.QUALITY_SCORE < 70 OR s.FINANCIAL_RISK = 'High' THEN 'High Risk'
       WHEN s.RISK_SCORE > 60 THEN 'Medium Risk' ELSE 'Low Risk' END AS RISK_CLASSIFICATION,
  CASE WHEN s.CATEGORY = 'Strategic' AND s.TIER_LEVEL = 1 AND s.ANNUAL_SPEND > 10000000
    THEN TRUE ELSE FALSE END AS IS_CRITICAL_SUPPLIER
FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_SUPPLIER s
WHERE s.IS_ACTIVE = TRUE;

-- ============================================================
-- V_DERIVED_INVENTORY_ALERTS
-- ============================================================
CREATE OR REPLACE VIEW V_DERIVED_INVENTORY_ALERTS AS
SELECT
  i.INVENTORY_ID, i.PART_ID, i.PLANT_ID, i.WAREHOUSE_ID,
  i.AVAILABLE_QTY, i.ON_HAND_QTY, i.RESERVED_QTY, i.TOTAL_VALUE,
  i.DAYS_OF_INVENTORY, i.REORDER_POINT, i.SAFETY_STOCK, i.MAX_STOCK_LEVEL,
  CASE WHEN i.AVAILABLE_QTY = 0 THEN 'Stockout'
       WHEN i.AVAILABLE_QTY < i.SAFETY_STOCK THEN 'Critical Low'
       WHEN i.AVAILABLE_QTY < i.REORDER_POINT THEN 'Below Reorder'
       WHEN i.AVAILABLE_QTY > i.MAX_STOCK_LEVEL THEN 'Overstocked'
       ELSE 'Normal' END AS INVENTORY_STATUS,
  CASE WHEN i.AVAILABLE_QTY < i.REORDER_POINT THEN TRUE ELSE FALSE END AS NEEDS_REORDER,
  CASE WHEN i.AVAILABLE_QTY > i.MAX_STOCK_LEVEL THEN TRUE ELSE FALSE END AS IS_OVERSTOCKED
FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_INVENTORY i;

-- ============================================================
-- V_DERIVED_PO_CYCLE_TIME
-- ============================================================
CREATE OR REPLACE VIEW V_DERIVED_PO_CYCLE_TIME AS
SELECT
  po.PO_ID, po.SUPPLIER_ID, po.PLANT_ID, po.ORDER_DATE, po.PROMISED_DATE, po.RECEIVED_DATE,
  po.TOTAL_VALUE, po.STATUS,
  CASE WHEN po.RECEIVED_DATE IS NOT NULL
    THEN DATEDIFF('day', po.ORDER_DATE, po.RECEIVED_DATE) ELSE NULL END AS CYCLE_TIME_DAYS,
  CASE WHEN po.RECEIVED_DATE IS NOT NULL AND po.PROMISED_DATE IS NOT NULL
    THEN DATEDIFF('day', po.PROMISED_DATE, po.RECEIVED_DATE) ELSE NULL END AS DAYS_LATE,
  CASE WHEN po.RECEIVED_DATE IS NOT NULL AND po.RECEIVED_DATE <= po.PROMISED_DATE THEN TRUE
       WHEN po.RECEIVED_DATE IS NOT NULL THEN FALSE ELSE NULL END AS PO_ON_TIME
FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_PURCHASE_ORDER po;

-- ============================================================
-- V_DERIVED_SHIPMENT_METRICS
-- ============================================================
CREATE OR REPLACE VIEW V_DERIVED_SHIPMENT_METRICS AS
SELECT
  sh.SHIPMENT_ID, sh.SHIPMENT_TYPE, sh.CARRIER_ID, sh.SUPPLIER_ID, sh.CUSTOMER_ID,
  sh.SHIP_DATE, sh.PROMISED_DELIVERY_DATE, sh.ACTUAL_DELIVERY_DATE,
  sh.FREIGHT_COST, sh.WEIGHT_KG, sh.STATUS, sh.IS_ON_TIME,
  CASE WHEN sh.ACTUAL_DELIVERY_DATE IS NOT NULL AND sh.SHIP_DATE IS NOT NULL
    THEN DATEDIFF('day', sh.SHIP_DATE, sh.ACTUAL_DELIVERY_DATE) ELSE NULL END AS TRANSIT_DAYS,
  CASE WHEN sh.ACTUAL_DELIVERY_DATE > sh.PROMISED_DELIVERY_DATE
    THEN DATEDIFF('day', sh.PROMISED_DELIVERY_DATE, sh.ACTUAL_DELIVERY_DATE) ELSE 0 END AS DAYS_LATE,
  CASE WHEN sh.WEIGHT_KG > 0 THEN ROUND(sh.FREIGHT_COST / sh.WEIGHT_KG, 2) ELSE NULL END AS COST_PER_KG
FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SHIPMENT sh;

-- ============================================================
-- V_DERIVED_WORK_ORDER_METRICS
-- ============================================================
CREATE OR REPLACE VIEW V_DERIVED_WORK_ORDER_METRICS AS
SELECT
  wo.WO_ID, wo.PART_ID, wo.PLANT_ID, wo.WORK_CENTER_ID, wo.STATUS,
  wo.QUANTITY_PLANNED, wo.QUANTITY_PRODUCED, wo.QUANTITY_SCRAPPED,
  wo.PLANNED_START_DATE, wo.ACTUAL_START_DATE, wo.PLANNED_END_DATE, wo.ACTUAL_END_DATE,
  CASE WHEN (wo.QUANTITY_PRODUCED + wo.QUANTITY_SCRAPPED) > 0
    THEN ROUND(wo.QUANTITY_PRODUCED * 100.0 / (wo.QUANTITY_PRODUCED + wo.QUANTITY_SCRAPPED), 2)
    ELSE NULL END AS YIELD_RATE_DERIVED,
  CASE WHEN wo.QUANTITY_PLANNED > 0
    THEN ROUND(wo.QUANTITY_SCRAPPED * 100.0 / wo.QUANTITY_PLANNED, 2) ELSE 0 END AS SCRAP_RATE,
  CASE WHEN wo.ACTUAL_END_DATE IS NOT NULL AND wo.PLANNED_END_DATE IS NOT NULL
    THEN DATEDIFF('day', wo.PLANNED_END_DATE, wo.ACTUAL_END_DATE) ELSE NULL END AS SCHEDULE_VARIANCE,
  CASE WHEN wo.ACTUAL_END_DATE <= wo.PLANNED_END_DATE THEN TRUE ELSE FALSE END AS ON_TIME_COMPLETION
FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_WORK_ORDER wo;

-- ============================================================
-- V_DERIVED_MATERIAL_REQUIREMENTS
-- ============================================================
CREATE OR REPLACE VIEW V_DERIVED_MATERIAL_REQUIREMENTS AS
SELECT
  wo.WO_ID,
  wo.PART_ID AS ASSEMBLY_PART_ID,
  p_asm.PART_NAME AS ASSEMBLY_NAME,
  bom.CHILD_PART_ID AS COMPONENT_PART_ID,
  p_cmp.PART_NAME AS COMPONENT_NAME,
  wo.QUANTITY_PLANNED AS WO_QUANTITY,
  bom.QUANTITY_PER,
  ROUND(wo.QUANTITY_PLANNED * bom.QUANTITY_PER, 2) AS REQUIRED_QTY,
  COALESCE(inv.AVAILABLE_QTY, 0) AS AVAILABLE_QTY,
  CASE WHEN COALESCE(inv.AVAILABLE_QTY, 0) >= ROUND(wo.QUANTITY_PLANNED * bom.QUANTITY_PER, 0)
    THEN 'Sufficient' ELSE 'Shortage' END AS MATERIAL_STATUS,
  wo.STATUS AS WO_STATUS,
  wo.PLANNED_START_DATE
FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_WORK_ORDER wo
JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_BOM bom ON wo.PART_ID = bom.PARENT_PART_ID
JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PART p_asm ON wo.PART_ID = p_asm.PART_ID
JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PART p_cmp ON bom.CHILD_PART_ID = p_cmp.PART_ID
LEFT JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_INVENTORY inv
  ON bom.CHILD_PART_ID = inv.PART_ID AND wo.PLANT_ID = inv.PLANT_ID
WHERE wo.STATUS IN ('Planned', 'In Progress', 'Released');

-- ============================================================
-- V_METRIC_ALERTS (RAG status for live KPIs)
-- ============================================================
CREATE OR REPLACE VIEW V_METRIC_ALERTS AS
WITH live_metrics AS (
  SELECT 'MET-001' AS METRIC_ID, 'On-Time Delivery' AS METRIC_NAME,
    COUNT(CASE WHEN IS_ON_TIME = TRUE THEN 1 END) * 100.0 / NULLIF(COUNT(*), 0) AS ACTUAL_VALUE
  FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SHIPMENT WHERE STATUS IN ('Delivered','Closed')
  UNION ALL
  SELECT 'MET-006', 'Production Yield',
    AVG(CASE WHEN (QUANTITY_PRODUCED + QUANTITY_SCRAPPED) > 0
      THEN QUANTITY_PRODUCED * 100.0 / (QUANTITY_PRODUCED + QUANTITY_SCRAPPED) END)
  FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_WORK_ORDER WHERE STATUS = 'Completed'
  UNION ALL
  SELECT 'MET-007', 'Scrap Rate',
    SUM(QUANTITY_SCRAPPED) * 100.0 / NULLIF(SUM(QUANTITY_PLANNED), 0)
  FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_WORK_ORDER
  UNION ALL
  SELECT 'MET-013', 'Quality Defect Rate',
    SUM(QUANTITY_DEFECTIVE) * 100.0 / NULLIF(SUM(QUANTITY_INSPECTED), 0)
  FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_QUALITY_EVENT
  UNION ALL
  SELECT 'MET-016', 'Stockout Rate',
    COUNT(CASE WHEN AVAILABLE_QTY = 0 THEN 1 END) * 100.0 / NULLIF(COUNT(*), 0)
  FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_INVENTORY
  UNION ALL
  SELECT 'MET-002', 'Fill Rate',
    SUM(QUANTITY_SHIPPED) * 100.0 / NULLIF(SUM(QUANTITY_ORDERED), 0)
  FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SALES_ORDER_LINE
  UNION ALL
  SELECT 'MET-009', 'WO Completion Rate',
    COUNT(CASE WHEN ACTUAL_END_DATE <= PLANNED_END_DATE THEN 1 END) * 100.0 / NULLIF(COUNT(*), 0)
  FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_WORK_ORDER WHERE STATUS = 'Completed'
)
SELECT
  lm.METRIC_ID, lm.METRIC_NAME, ROUND(lm.ACTUAL_VALUE, 2) AS ACTUAL_VALUE,
  t.GREEN_MIN AS TARGET_VALUE, t.DIRECTION,
  CASE
    WHEN t.DIRECTION = 'HIGHER_BETTER' AND lm.ACTUAL_VALUE >= t.GREEN_MIN THEN 'GREEN'
    WHEN t.DIRECTION = 'HIGHER_BETTER' AND lm.ACTUAL_VALUE >= t.YELLOW_MIN THEN 'YELLOW'
    WHEN t.DIRECTION = 'LOWER_BETTER' AND lm.ACTUAL_VALUE <= t.GREEN_MAX THEN 'GREEN'
    WHEN t.DIRECTION = 'LOWER_BETTER' AND lm.ACTUAL_VALUE <= t.YELLOW_MAX THEN 'YELLOW'
    WHEN t.DIRECTION = 'RANGE' AND lm.ACTUAL_VALUE BETWEEN t.GREEN_MIN AND t.GREEN_MAX THEN 'GREEN'
    WHEN t.DIRECTION = 'RANGE' AND lm.ACTUAL_VALUE BETWEEN t.YELLOW_MIN AND t.YELLOW_MAX THEN 'YELLOW'
    ELSE 'RED'
  END AS RAG_STATUS
FROM live_metrics lm
JOIN AEROSPACE_SUPPLY_CHAIN_AI.ANALYTICS.METRIC_THRESHOLDS t ON lm.METRIC_ID = t.METRIC_ID;

-- ============================================================
-- V_INTEGRITY_CONSTRAINT_VIOLATIONS (data quality checks)
-- ============================================================
CREATE OR REPLACE VIEW V_INTEGRITY_CONSTRAINT_VIOLATIONS AS
SELECT 'IC-01' AS CONSTRAINT_ID, 'PO references inactive supplier' AS DESCRIPTION,
  'FACT_PURCHASE_ORDER -> DIM_SUPPLIER' AS ENTITY_PATH, COUNT(*) AS VIOLATION_COUNT
FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_PURCHASE_ORDER po
LEFT JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_SUPPLIER s ON po.SUPPLIER_ID = s.SUPPLIER_ID
WHERE s.IS_ACTIVE = FALSE
UNION ALL
SELECT 'IC-02', 'SO references inactive customer', 'FACT_SALES_ORDER -> DIM_CUSTOMER', COUNT(*)
FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SALES_ORDER so
LEFT JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_CUSTOMER c ON so.CUSTOMER_ID = c.CUSTOMER_ID
WHERE c.CONTRACT_STATUS = 'Inactive'
UNION ALL
SELECT 'IC-03', 'Negative inventory quantity', 'FACT_INVENTORY', COUNT(*)
FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_INVENTORY WHERE AVAILABLE_QTY < 0 OR ON_HAND_QTY < 0
UNION ALL
SELECT 'IC-04', 'BOM self-referencing (parent = child)', 'DIM_BOM', COUNT(*)
FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_BOM WHERE PARENT_PART_ID = CHILD_PART_ID
UNION ALL
SELECT 'IC-05', 'Shipment dates not chronological (ship > delivery)', 'FACT_SHIPMENT', COUNT(*)
FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SHIPMENT WHERE ACTUAL_DELIVERY_DATE IS NOT NULL AND SHIP_DATE > ACTUAL_DELIVERY_DATE
UNION ALL
SELECT 'IC-06', 'Work order planned dates not sequential (start > end)', 'FACT_WORK_ORDER', COUNT(*)
FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_WORK_ORDER WHERE PLANNED_START_DATE > PLANNED_END_DATE
UNION ALL
SELECT 'IC-07', 'Quality event references non-existent part', 'FACT_QUALITY_EVENT -> DIM_PART', COUNT(*)
FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_QUALITY_EVENT qe
LEFT JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PART p ON qe.PART_ID = p.PART_ID
WHERE p.PART_ID IS NULL
UNION ALL
SELECT 'IC-08', 'ITAR export control validation (placeholder)', 'FACT_SHIPMENT + DIM_PART', 0;

-- ============================================================
-- V_ONTOLOGY_HEALTH_SUMMARY
-- ============================================================
CREATE OR REPLACE VIEW V_ONTOLOGY_HEALTH_SUMMARY AS
SELECT
  COUNT(*) AS TOTAL_CONSTRAINTS,
  COUNT(CASE WHEN VIOLATION_COUNT = 0 THEN 1 END) AS CONSTRAINTS_PASSING,
  COUNT(CASE WHEN VIOLATION_COUNT > 0 THEN 1 END) AS CONSTRAINTS_VIOLATED,
  SUM(VIOLATION_COUNT) AS TOTAL_VIOLATIONS,
  ROUND(COUNT(CASE WHEN VIOLATION_COUNT = 0 THEN 1 END) * 100.0 / COUNT(*), 1) AS COMPLIANCE_PCT,
  CASE WHEN COUNT(CASE WHEN VIOLATION_COUNT > 0 AND CONSTRAINT_ID IN ('IC-01','IC-02','IC-03','IC-04','IC-07') THEN 1 END) = 0
    THEN 'HEALTHY - Critical constraints passing'
    ELSE 'NEEDS ATTENTION - Critical constraint violations' END AS HEALTH_STATUS
FROM AEROSPACE_SUPPLY_CHAIN_AI.ANALYTICS.V_INTEGRITY_CONSTRAINT_VIOLATIONS;
