-- Semantic views for Cortex Analyst (domain-specific analytics)
-- Co-authored with CoCo

USE DATABASE AEROSPACE_SUPPLY_CHAIN_AI;
USE SCHEMA SEMANTIC;

-- ============================================================
-- SV_PROCUREMENT - Supplier and purchase order analytics
-- ============================================================
CREATE OR REPLACE SEMANTIC VIEW SV_PROCUREMENT
    TABLES (
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_SUPPLIER UNIQUE (SUPPLIER_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PART UNIQUE (PART_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_PURCHASE_ORDER UNIQUE (PO_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_PURCHASE_ORDER_LINE UNIQUE (PO_LINE_ID)
    )
    RELATIONSHIPS (
        PO_TO_SUPPLIER AS FACT_PURCHASE_ORDER(SUPPLIER_ID) REFERENCES DIM_SUPPLIER(SUPPLIER_ID),
        PO_LINE_TO_PART AS FACT_PURCHASE_ORDER_LINE(PART_ID) REFERENCES DIM_PART(PART_ID),
        PO_LINE_TO_PO AS FACT_PURCHASE_ORDER_LINE(PO_ID) REFERENCES FACT_PURCHASE_ORDER(PO_ID)
    )
    FACTS (
        DIM_SUPPLIER.RISK_SCORE AS RISK_SCORE,
        DIM_SUPPLIER.QUALITY_SCORE AS QUALITY_SCORE,
        DIM_SUPPLIER.DELIVERY_SCORE AS DELIVERY_SCORE,
        DIM_SUPPLIER.ANNUAL_SPEND AS ANNUAL_SPEND,
        DIM_PART.UNIT_COST AS UNIT_COST,
        FACT_PURCHASE_ORDER.TOTAL_VALUE AS TOTAL_VALUE,
        FACT_PURCHASE_ORDER_LINE.QUANTITY_ORDERED AS QUANTITY_ORDERED,
        FACT_PURCHASE_ORDER_LINE.QUANTITY_RECEIVED AS QUANTITY_RECEIVED,
        FACT_PURCHASE_ORDER_LINE.UNIT_PRICE AS UNIT_PRICE,
        FACT_PURCHASE_ORDER_LINE.LINE_VALUE AS LINE_VALUE,
        FACT_PURCHASE_ORDER_LINE.FREIGHT_COST AS FREIGHT_COST,
        FACT_PURCHASE_ORDER_LINE.LANDED_COST AS LANDED_COST
    )
    DIMENSIONS (
        DIM_SUPPLIER.SUPPLIER_ID AS SUPPLIER_ID,
        DIM_SUPPLIER.SUPPLIER_NAME AS SUPPLIER_NAME,
        DIM_SUPPLIER.COUNTRY AS COUNTRY,
        DIM_SUPPLIER.REGION AS REGION,
        DIM_SUPPLIER.TIER_LEVEL AS TIER_LEVEL,
        DIM_SUPPLIER.CATEGORY AS CATEGORY,
        DIM_SUPPLIER.FINANCIAL_RISK AS FINANCIAL_RISK,
        DIM_SUPPLIER.CERTIFICATION_STATUS AS CERTIFICATION_STATUS,
        DIM_SUPPLIER.IS_ACTIVE AS IS_ACTIVE,
        DIM_PART.PART_ID AS PART_ID,
        DIM_PART.PART_NAME AS PART_NAME,
        DIM_PART.PART_FAMILY AS PART_FAMILY,
        DIM_PART.ATA_CHAPTER AS ATA_CHAPTER,
        DIM_PART.CRITICALITY AS CRITICALITY,
        FACT_PURCHASE_ORDER.PO_ID AS PO_ID,
        FACT_PURCHASE_ORDER.SUPPLIER_ID AS SUPPLIER_ID,
        FACT_PURCHASE_ORDER.PLANT_ID AS PLANT_ID,
        FACT_PURCHASE_ORDER.STATUS AS STATUS,
        FACT_PURCHASE_ORDER.PRIORITY AS PRIORITY,
        FACT_PURCHASE_ORDER.ORDER_DATE AS ORDER_DATE,
        FACT_PURCHASE_ORDER.PROMISED_DATE AS PROMISED_DATE,
        FACT_PURCHASE_ORDER.RECEIVED_DATE AS RECEIVED_DATE,
        FACT_PURCHASE_ORDER_LINE.PO_LINE_ID AS PO_LINE_ID,
        FACT_PURCHASE_ORDER_LINE.PO_ID AS PO_ID,
        FACT_PURCHASE_ORDER_LINE.PART_ID AS PART_ID
    )
    COMMENT = 'Procurement and supplier analytics: purchase orders, supplier performance, OTD, spend, landed cost, risk scores.'
    AI_VERIFIED_QUERIES (
        "Top suppliers by spend" AS (
            QUESTION 'Who are the top 10 suppliers by total procurement spend?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT s.SUPPLIER_NAME, SUM(po.TOTAL_VALUE) AS TOTAL_SPEND FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_PURCHASE_ORDER po JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_SUPPLIER s ON po.SUPPLIER_ID = s.SUPPLIER_ID GROUP BY s.SUPPLIER_NAME ORDER BY TOTAL_SPEND DESC LIMIT 10'
        ),
        "Suppliers below 90% OTD" AS (
            QUESTION 'Which suppliers have delivery score below 90%?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT SUPPLIER_NAME, DELIVERY_SCORE, RISK_SCORE FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_SUPPLIER WHERE DELIVERY_SCORE < 90 AND IS_ACTIVE = TRUE ORDER BY DELIVERY_SCORE'
        ),
        "Procurement spend by quarter" AS (
            QUESTION 'What is our procurement spend by quarter this year?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT QUARTER(ORDER_DATE) AS QTR, SUM(TOTAL_VALUE) AS SPEND FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_PURCHASE_ORDER WHERE YEAR(ORDER_DATE) = 2026 GROUP BY QTR ORDER BY QTR'
        )
    );

-- ============================================================
-- SV_INVENTORY - Stock levels and movement analytics
-- ============================================================
CREATE OR REPLACE SEMANTIC VIEW SV_INVENTORY
    TABLES (
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PART UNIQUE (PART_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PLANT UNIQUE (PLANT_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_WAREHOUSE UNIQUE (WAREHOUSE_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_INVENTORY UNIQUE (INVENTORY_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_INVENTORY_MOVEMENT UNIQUE (MOVEMENT_ID)
    )
    RELATIONSHIPS (
        INVENTORY_TO_PART AS FACT_INVENTORY(PART_ID) REFERENCES DIM_PART(PART_ID),
        INVENTORY_TO_PLANT AS FACT_INVENTORY(PLANT_ID) REFERENCES DIM_PLANT(PLANT_ID),
        INVENTORY_TO_WAREHOUSE AS FACT_INVENTORY(WAREHOUSE_ID) REFERENCES DIM_WAREHOUSE(WAREHOUSE_ID)
    )
    FACTS (
        FACT_INVENTORY.AVAILABLE_QTY AS AVAILABLE_QTY,
        FACT_INVENTORY.ON_HAND_QTY AS ON_HAND_QTY,
        FACT_INVENTORY.RESERVED_QTY AS RESERVED_QTY,
        FACT_INVENTORY.TOTAL_VALUE AS TOTAL_VALUE,
        FACT_INVENTORY.DAYS_OF_INVENTORY AS DAYS_OF_INVENTORY,
        FACT_INVENTORY.REORDER_POINT AS REORDER_POINT,
        FACT_INVENTORY.SAFETY_STOCK AS SAFETY_STOCK,
        FACT_INVENTORY.MAX_STOCK_LEVEL AS MAX_STOCK_LEVEL,
        FACT_INVENTORY_MOVEMENT.QUANTITY AS QUANTITY
    )
    DIMENSIONS (
        DIM_PART.PART_ID AS PART_ID,
        DIM_PART.PART_NAME AS PART_NAME,
        DIM_PART.PART_FAMILY AS PART_FAMILY,
        DIM_PART.CRITICALITY AS CRITICALITY,
        DIM_PLANT.PLANT_ID AS PLANT_ID,
        DIM_PLANT.PLANT_NAME AS PLANT_NAME,
        DIM_PLANT.COUNTRY AS COUNTRY,
        DIM_PLANT.REGION AS REGION,
        DIM_WAREHOUSE.WAREHOUSE_ID AS WAREHOUSE_ID,
        DIM_WAREHOUSE.WAREHOUSE_NAME AS WAREHOUSE_NAME,
        DIM_WAREHOUSE.WAREHOUSE_TYPE AS WAREHOUSE_TYPE,
        FACT_INVENTORY.INVENTORY_ID AS INVENTORY_ID,
        FACT_INVENTORY.PART_ID AS PART_ID,
        FACT_INVENTORY.PLANT_ID AS PLANT_ID,
        FACT_INVENTORY.WAREHOUSE_ID AS WAREHOUSE_ID,
        FACT_INVENTORY.SNAPSHOT_DATE AS SNAPSHOT_DATE,
        FACT_INVENTORY_MOVEMENT.MOVEMENT_ID AS MOVEMENT_ID,
        FACT_INVENTORY_MOVEMENT.MOVEMENT_TYPE AS MOVEMENT_TYPE,
        FACT_INVENTORY_MOVEMENT.PART_ID AS PART_ID,
        FACT_INVENTORY_MOVEMENT.PLANT_ID AS PLANT_ID,
        FACT_INVENTORY_MOVEMENT.MOVEMENT_DATE AS MOVEMENT_DATE
    )
    COMMENT = 'Inventory management analytics: stock levels, days of inventory, movements, warehouse utilization, reorder alerts.'
    AI_VERIFIED_QUERIES (
        "Parts below reorder point" AS (
            QUESTION 'Which parts are below their reorder point?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT p.PART_NAME, i.AVAILABLE_QTY, i.REORDER_POINT, i.SAFETY_STOCK FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_INVENTORY i JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PART p ON i.PART_ID = p.PART_ID WHERE i.AVAILABLE_QTY < i.REORDER_POINT ORDER BY i.AVAILABLE_QTY'
        ),
        "Average DOI by plant" AS (
            QUESTION 'What is the average days of inventory by plant?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT pl.PLANT_NAME, ROUND(AVG(i.DAYS_OF_INVENTORY), 1) AS AVG_DOI FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_INVENTORY i JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PLANT pl ON i.PLANT_ID = pl.PLANT_ID GROUP BY pl.PLANT_NAME ORDER BY AVG_DOI'
        ),
        "Inventory value by warehouse type" AS (
            QUESTION 'What is total inventory value by warehouse type?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT w.WAREHOUSE_TYPE, SUM(i.TOTAL_VALUE) AS TOTAL_VALUE FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_INVENTORY i JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_WAREHOUSE w ON i.WAREHOUSE_ID = w.WAREHOUSE_ID GROUP BY w.WAREHOUSE_TYPE ORDER BY TOTAL_VALUE DESC'
        )
    );

-- ============================================================
-- SV_MANUFACTURING - Production yield and work order analytics
-- ============================================================
CREATE OR REPLACE SEMANTIC VIEW SV_MANUFACTURING
    TABLES (
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PART UNIQUE (PART_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PLANT UNIQUE (PLANT_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_WORK_CENTER UNIQUE (WORK_CENTER_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_WORK_ORDER UNIQUE (WO_ID)
    )
    RELATIONSHIPS (
        WO_TO_PART AS FACT_WORK_ORDER(PART_ID) REFERENCES DIM_PART(PART_ID),
        WO_TO_PLANT AS FACT_WORK_ORDER(PLANT_ID) REFERENCES DIM_PLANT(PLANT_ID),
        WO_TO_WORK_CENTER AS FACT_WORK_ORDER(WORK_CENTER_ID) REFERENCES DIM_WORK_CENTER(WORK_CENTER_ID)
    )
    FACTS (
        DIM_WORK_CENTER.CAPACITY_HOURS_PER_DAY AS CAPACITY_HOURS_PER_DAY,
        FACT_WORK_ORDER.QUANTITY_PLANNED AS QUANTITY_PLANNED,
        FACT_WORK_ORDER.QUANTITY_PRODUCED AS QUANTITY_PRODUCED,
        FACT_WORK_ORDER.QUANTITY_SCRAPPED AS QUANTITY_SCRAPPED,
        FACT_WORK_ORDER.YIELD_RATE AS YIELD_RATE
    )
    DIMENSIONS (
        DIM_PART.PART_ID AS PART_ID,
        DIM_PART.PART_NAME AS PART_NAME,
        DIM_PART.PART_FAMILY AS PART_FAMILY,
        DIM_PLANT.PLANT_ID AS PLANT_ID,
        DIM_PLANT.PLANT_NAME AS PLANT_NAME,
        DIM_PLANT.REGION AS REGION,
        DIM_WORK_CENTER.WORK_CENTER_ID AS WORK_CENTER_ID,
        DIM_WORK_CENTER.WORK_CENTER_NAME AS WORK_CENTER_NAME,
        DIM_WORK_CENTER.WORK_CENTER_TYPE AS WORK_CENTER_TYPE,
        FACT_WORK_ORDER.WO_ID AS WO_ID,
        FACT_WORK_ORDER.PART_ID AS PART_ID,
        FACT_WORK_ORDER.PLANT_ID AS PLANT_ID,
        FACT_WORK_ORDER.WORK_CENTER_ID AS WORK_CENTER_ID,
        FACT_WORK_ORDER.STATUS AS STATUS,
        FACT_WORK_ORDER.WO_TYPE AS WO_TYPE,
        FACT_WORK_ORDER.PROGRAM AS PROGRAM,
        FACT_WORK_ORDER.ORDER_DATE AS ORDER_DATE,
        FACT_WORK_ORDER.PLANNED_START_DATE AS PLANNED_START_DATE,
        FACT_WORK_ORDER.PLANNED_END_DATE AS PLANNED_END_DATE,
        FACT_WORK_ORDER.ACTUAL_END_DATE AS ACTUAL_END_DATE
    )
    COMMENT = 'Manufacturing analytics: production yield, scrap rate, work order completion, capacity utilization by plant and work center.'
    AI_VERIFIED_QUERIES (
        "Yield by plant" AS (
            QUESTION 'What is the average production yield by plant?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT pl.PLANT_NAME, ROUND(AVG(wo.YIELD_RATE), 2) AS AVG_YIELD FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_WORK_ORDER wo JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PLANT pl ON wo.PLANT_ID = pl.PLANT_ID WHERE wo.STATUS = ''Completed'' GROUP BY pl.PLANT_NAME ORDER BY AVG_YIELD'
        ),
        "Scrap by work center type" AS (
            QUESTION 'What is the scrap rate by work center type?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT wc.WORK_CENTER_TYPE, ROUND(SUM(wo.QUANTITY_SCRAPPED)*100.0/NULLIF(SUM(wo.QUANTITY_PLANNED),0), 2) AS SCRAP_RATE FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_WORK_ORDER wo JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_WORK_CENTER wc ON wo.WORK_CENTER_ID = wc.WORK_CENTER_ID GROUP BY wc.WORK_CENTER_TYPE ORDER BY SCRAP_RATE DESC'
        ),
        "Parts below 95% yield" AS (
            QUESTION 'Which parts have yield below 95%?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT p.PART_NAME, ROUND(AVG(wo.YIELD_RATE), 2) AS AVG_YIELD FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_WORK_ORDER wo JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PART p ON wo.PART_ID = p.PART_ID WHERE wo.STATUS = ''Completed'' GROUP BY p.PART_NAME HAVING AVG(wo.YIELD_RATE) < 95 ORDER BY AVG_YIELD'
        )
    );

-- ============================================================
-- SV_QUALITY - Defect tracking and COPQ analytics
-- ============================================================
CREATE OR REPLACE SEMANTIC VIEW SV_QUALITY
    TABLES (
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PART UNIQUE (PART_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_SUPPLIER UNIQUE (SUPPLIER_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PLANT UNIQUE (PLANT_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_QUALITY_EVENT UNIQUE (QE_ID)
    )
    RELATIONSHIPS (
        QE_TO_PART AS FACT_QUALITY_EVENT(PART_ID) REFERENCES DIM_PART(PART_ID),
        QE_TO_PLANT AS FACT_QUALITY_EVENT(PLANT_ID) REFERENCES DIM_PLANT(PLANT_ID),
        QE_TO_SUPPLIER AS FACT_QUALITY_EVENT(SUPPLIER_ID) REFERENCES DIM_SUPPLIER(SUPPLIER_ID)
    )
    FACTS (
        FACT_QUALITY_EVENT.QUANTITY_INSPECTED AS QUANTITY_INSPECTED,
        FACT_QUALITY_EVENT.QUANTITY_DEFECTIVE AS QUANTITY_DEFECTIVE,
        FACT_QUALITY_EVENT.COST_OF_QUALITY AS COST_OF_QUALITY
    )
    DIMENSIONS (
        DIM_PART.PART_ID AS PART_ID,
        DIM_PART.PART_NAME AS PART_NAME,
        DIM_PART.PART_FAMILY AS PART_FAMILY,
        DIM_SUPPLIER.SUPPLIER_ID AS SUPPLIER_ID,
        DIM_SUPPLIER.SUPPLIER_NAME AS SUPPLIER_NAME,
        DIM_PLANT.PLANT_ID AS PLANT_ID,
        DIM_PLANT.PLANT_NAME AS PLANT_NAME,
        FACT_QUALITY_EVENT.QE_ID AS QE_ID,
        FACT_QUALITY_EVENT.PART_ID AS PART_ID,
        FACT_QUALITY_EVENT.SUPPLIER_ID AS SUPPLIER_ID,
        FACT_QUALITY_EVENT.PLANT_ID AS PLANT_ID,
        FACT_QUALITY_EVENT.EVENT_TYPE AS EVENT_TYPE,
        FACT_QUALITY_EVENT.SEVERITY AS SEVERITY,
        FACT_QUALITY_EVENT.DEFECT_TYPE AS DEFECT_TYPE,
        FACT_QUALITY_EVENT.ROOT_CAUSE AS ROOT_CAUSE,
        FACT_QUALITY_EVENT.DISPOSITION AS DISPOSITION,
        FACT_QUALITY_EVENT.STATUS AS STATUS,
        FACT_QUALITY_EVENT.EVENT_DATE AS EVENT_DATE,
        FACT_QUALITY_EVENT.RESOLUTION_DATE AS RESOLUTION_DATE
    )
    COMMENT = 'Quality analytics: defect tracking, cost of poor quality, root cause analysis, supplier quality, resolution times.'
    AI_VERIFIED_QUERIES (
        "Defect rate by supplier" AS (
            QUESTION 'What is the defect rate by supplier?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT s.SUPPLIER_NAME, ROUND(SUM(q.QUANTITY_DEFECTIVE)*100.0/NULLIF(SUM(q.QUANTITY_INSPECTED),0), 2) AS DEFECT_RATE FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_QUALITY_EVENT q JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_SUPPLIER s ON q.SUPPLIER_ID = s.SUPPLIER_ID GROUP BY s.SUPPLIER_NAME ORDER BY DEFECT_RATE DESC LIMIT 10'
        ),
        "COPQ by quarter" AS (
            QUESTION 'What is the cost of poor quality by quarter?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT QUARTER(EVENT_DATE) AS QTR, SUM(COST_OF_QUALITY) AS TOTAL_COPQ FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_QUALITY_EVENT WHERE YEAR(EVENT_DATE) = 2026 GROUP BY QTR ORDER BY QTR'
        ),
        "Common root causes" AS (
            QUESTION 'What are the most common root causes of defects?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT ROOT_CAUSE, COUNT(*) AS EVENT_COUNT, SUM(COST_OF_QUALITY) AS TOTAL_COST FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_QUALITY_EVENT GROUP BY ROOT_CAUSE ORDER BY EVENT_COUNT DESC'
        )
    );

-- ============================================================
-- SV_SALES - Order fulfillment and revenue analytics
-- ============================================================
CREATE OR REPLACE SEMANTIC VIEW SV_SALES
    TABLES (
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_CUSTOMER UNIQUE (CUSTOMER_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PART UNIQUE (PART_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SALES_ORDER UNIQUE (SO_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SALES_ORDER_LINE UNIQUE (SO_LINE_ID)
    )
    RELATIONSHIPS (
        SO_TO_CUSTOMER AS FACT_SALES_ORDER(CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID),
        SO_LINE_TO_PART AS FACT_SALES_ORDER_LINE(PART_ID) REFERENCES DIM_PART(PART_ID),
        SO_LINE_TO_SO AS FACT_SALES_ORDER_LINE(SO_ID) REFERENCES FACT_SALES_ORDER(SO_ID)
    )
    FACTS (
        DIM_CUSTOMER.ANNUAL_REVENUE AS ANNUAL_REVENUE,
        FACT_SALES_ORDER.TOTAL_VALUE AS TOTAL_VALUE,
        FACT_SALES_ORDER_LINE.QUANTITY_ORDERED AS QUANTITY_ORDERED,
        FACT_SALES_ORDER_LINE.QUANTITY_SHIPPED AS QUANTITY_SHIPPED,
        FACT_SALES_ORDER_LINE.LINE_VALUE AS LINE_VALUE,
        FACT_SALES_ORDER_LINE.BACKORDER_QTY AS BACKORDER_QTY
    )
    DIMENSIONS (
        DIM_CUSTOMER.CUSTOMER_ID AS CUSTOMER_ID,
        DIM_CUSTOMER.CUSTOMER_NAME AS CUSTOMER_NAME,
        DIM_CUSTOMER.CUSTOMER_TYPE AS CUSTOMER_TYPE,
        DIM_CUSTOMER.COUNTRY AS COUNTRY,
        DIM_CUSTOMER.REGION AS REGION,
        DIM_CUSTOMER.REVENUE_TIER AS REVENUE_TIER,
        DIM_PART.PART_ID AS PART_ID,
        DIM_PART.PART_NAME AS PART_NAME,
        DIM_PART.PART_FAMILY AS PART_FAMILY,
        FACT_SALES_ORDER.SO_ID AS SO_ID,
        FACT_SALES_ORDER.CUSTOMER_ID AS CUSTOMER_ID,
        FACT_SALES_ORDER.STATUS AS STATUS,
        FACT_SALES_ORDER.PRIORITY AS PRIORITY,
        FACT_SALES_ORDER.ORDER_DATE AS ORDER_DATE,
        FACT_SALES_ORDER.PROMISED_DATE AS PROMISED_DATE,
        FACT_SALES_ORDER_LINE.SO_LINE_ID AS SO_LINE_ID,
        FACT_SALES_ORDER_LINE.SO_ID AS SO_ID,
        FACT_SALES_ORDER_LINE.PART_ID AS PART_ID
    )
    COMMENT = 'Sales and customer analytics: order fulfillment, revenue, fill rates, customer analysis, delivery performance.'
    AI_VERIFIED_QUERIES (
        "Fill rate by customer type" AS (
            QUESTION 'What is the fill rate by customer type?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT c.CUSTOMER_TYPE, ROUND(SUM(sol.QUANTITY_SHIPPED)*100.0/NULLIF(SUM(sol.QUANTITY_ORDERED),0), 2) AS FILL_RATE FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SALES_ORDER_LINE sol JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SALES_ORDER so ON sol.SO_ID = so.SO_ID JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_CUSTOMER c ON so.CUSTOMER_ID = c.CUSTOMER_ID GROUP BY c.CUSTOMER_TYPE ORDER BY FILL_RATE DESC'
        ),
        "Revenue by customer tier" AS (
            QUESTION 'What is total revenue by customer tier?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT c.REVENUE_TIER, SUM(so.TOTAL_VALUE) AS REVENUE FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SALES_ORDER so JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_CUSTOMER c ON so.CUSTOMER_ID = c.CUSTOMER_ID GROUP BY c.REVENUE_TIER ORDER BY REVENUE DESC'
        ),
        "Top customers by value" AS (
            QUESTION 'Who are our top 10 customers by order value?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT c.CUSTOMER_NAME, SUM(so.TOTAL_VALUE) AS TOTAL_ORDERS FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SALES_ORDER so JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_CUSTOMER c ON so.CUSTOMER_ID = c.CUSTOMER_ID GROUP BY c.CUSTOMER_NAME ORDER BY TOTAL_ORDERS DESC LIMIT 10'
        )
    );
