-- Cross-domain semantic views for multi-domain analytics
-- Co-authored with CoCo

USE DATABASE AEROSPACE_SUPPLY_CHAIN_AI;
USE SCHEMA SEMANTIC;

-- ============================================================
-- SUPPLIER_QUALITY_PRODUCTION_SV - Root cause analysis
-- ============================================================
CREATE OR REPLACE SEMANTIC VIEW SUPPLIER_QUALITY_PRODUCTION_SV
    TABLES (
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_SUPPLIER UNIQUE (SUPPLIER_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PART UNIQUE (PART_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PLANT UNIQUE (PLANT_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_QUALITY_EVENT UNIQUE (QE_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_WORK_ORDER UNIQUE (WO_ID)
    )
    RELATIONSHIPS (
        QUALITY_TO_PART AS FACT_QUALITY_EVENT(PART_ID) REFERENCES DIM_PART(PART_ID),
        QUALITY_TO_PLANT AS FACT_QUALITY_EVENT(PLANT_ID) REFERENCES DIM_PLANT(PLANT_ID),
        QUALITY_TO_SUPPLIER AS FACT_QUALITY_EVENT(SUPPLIER_ID) REFERENCES DIM_SUPPLIER(SUPPLIER_ID),
        WO_TO_PART AS FACT_WORK_ORDER(PART_ID) REFERENCES DIM_PART(PART_ID),
        WO_TO_PLANT AS FACT_WORK_ORDER(PLANT_ID) REFERENCES DIM_PLANT(PLANT_ID)
    )
    FACTS (
        FACT_QUALITY_EVENT.QUANTITY_DEFECTIVE AS QUANTITY_DEFECTIVE,
        FACT_QUALITY_EVENT.COST_OF_QUALITY AS COST_OF_QUALITY,
        FACT_WORK_ORDER.QUANTITY_SCRAPPED AS QUANTITY_SCRAPPED,
        FACT_WORK_ORDER.YIELD_RATE AS YIELD_RATE
    )
    DIMENSIONS (
        DIM_SUPPLIER.SUPPLIER_ID AS SUPPLIER_ID,
        DIM_SUPPLIER.SUPPLIER_NAME AS SUPPLIER_NAME,
        DIM_SUPPLIER.TIER_LEVEL AS TIER_LEVEL,
        DIM_PART.PART_ID AS PART_ID,
        DIM_PART.PART_NAME AS PART_NAME,
        DIM_PART.PART_FAMILY AS PART_FAMILY,
        DIM_PLANT.PLANT_ID AS PLANT_ID,
        DIM_PLANT.PLANT_NAME AS PLANT_NAME,
        FACT_QUALITY_EVENT.QE_ID AS QE_ID,
        FACT_QUALITY_EVENT.SUPPLIER_ID AS SUPPLIER_ID,
        FACT_QUALITY_EVENT.PART_ID AS PART_ID,
        FACT_QUALITY_EVENT.PLANT_ID AS PLANT_ID,
        FACT_QUALITY_EVENT.SEVERITY AS SEVERITY,
        FACT_QUALITY_EVENT.DEFECT_TYPE AS DEFECT_TYPE,
        FACT_QUALITY_EVENT.EVENT_DATE AS EVENT_DATE,
        FACT_WORK_ORDER.WO_ID AS WO_ID,
        FACT_WORK_ORDER.PART_ID AS PART_ID,
        FACT_WORK_ORDER.PLANT_ID AS PLANT_ID,
        FACT_WORK_ORDER.STATUS AS STATUS
    )
    COMMENT = 'Cross-domain view linking supplier performance to quality events and production outcomes for root cause analysis.'
    AI_VERIFIED_QUERIES (
        "Suppliers causing most scrap" AS (
            QUESTION 'Which suppliers are causing the most production scrap?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT s.SUPPLIER_NAME, COUNT(q.QE_ID) AS QUALITY_EVENTS, SUM(q.COST_OF_QUALITY) AS TOTAL_COPQ FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_QUALITY_EVENT q JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_SUPPLIER s ON q.SUPPLIER_ID = s.SUPPLIER_ID GROUP BY s.SUPPLIER_NAME ORDER BY TOTAL_COPQ DESC LIMIT 10'
        )
    );

-- ============================================================
-- ORDER_SHIPMENT_CUSTOMER_SV - End-to-end fulfillment
-- ============================================================
CREATE OR REPLACE SEMANTIC VIEW ORDER_SHIPMENT_CUSTOMER_SV
    TABLES (
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_CUSTOMER UNIQUE (CUSTOMER_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_CARRIER UNIQUE (CARRIER_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SHIPMENT UNIQUE (SHIPMENT_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SALES_ORDER UNIQUE (SO_ID)
    )
    RELATIONSHIPS (
        SHIPMENT_TO_CARRIER AS FACT_SHIPMENT(CARRIER_ID) REFERENCES DIM_CARRIER(CARRIER_ID),
        SHIPMENT_TO_CUSTOMER AS FACT_SHIPMENT(CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID),
        SO_TO_CUSTOMER AS FACT_SALES_ORDER(CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID)
    )
    FACTS (
        DIM_CARRIER.ON_TIME_RATE AS ON_TIME_RATE,
        FACT_SHIPMENT.FREIGHT_COST AS FREIGHT_COST,
        FACT_SHIPMENT.WEIGHT_KG AS WEIGHT_KG,
        FACT_SALES_ORDER.TOTAL_VALUE AS TOTAL_VALUE
    )
    DIMENSIONS (
        DIM_CUSTOMER.CUSTOMER_ID AS CUSTOMER_ID,
        DIM_CUSTOMER.CUSTOMER_NAME AS CUSTOMER_NAME,
        DIM_CUSTOMER.CUSTOMER_TYPE AS CUSTOMER_TYPE,
        DIM_CUSTOMER.REVENUE_TIER AS REVENUE_TIER,
        DIM_CARRIER.CARRIER_ID AS CARRIER_ID,
        DIM_CARRIER.CARRIER_NAME AS CARRIER_NAME,
        DIM_CARRIER.SERVICE_TYPE AS SERVICE_TYPE,
        FACT_SHIPMENT.SHIPMENT_ID AS SHIPMENT_ID,
        FACT_SHIPMENT.SHIPMENT_TYPE AS SHIPMENT_TYPE,
        FACT_SHIPMENT.CARRIER_ID AS CARRIER_ID,
        FACT_SHIPMENT.CUSTOMER_ID AS CUSTOMER_ID,
        FACT_SHIPMENT.STATUS AS STATUS,
        FACT_SHIPMENT.IS_ON_TIME AS IS_ON_TIME,
        FACT_SHIPMENT.SHIP_DATE AS SHIP_DATE,
        FACT_SHIPMENT.PROMISED_DELIVERY_DATE AS PROMISED_DELIVERY_DATE,
        FACT_SHIPMENT.ACTUAL_DELIVERY_DATE AS ACTUAL_DELIVERY_DATE,
        FACT_SALES_ORDER.SO_ID AS SO_ID,
        FACT_SALES_ORDER.CUSTOMER_ID AS CUSTOMER_ID,
        FACT_SALES_ORDER.STATUS AS STATUS,
        FACT_SALES_ORDER.ORDER_DATE AS ORDER_DATE
    )
    COMMENT = 'Cross-domain end-to-end fulfillment: links customer orders to shipments and carriers for perfect order analysis.'
    AI_VERIFIED_QUERIES (
        "Customer OTD by tier" AS (
            QUESTION 'What is customer on-time delivery by revenue tier?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT c.REVENUE_TIER, ROUND(COUNT(CASE WHEN sh.IS_ON_TIME THEN 1 END)*100.0/NULLIF(COUNT(*),0), 2) AS OTD_PCT FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SHIPMENT sh JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_CUSTOMER c ON sh.CUSTOMER_ID = c.CUSTOMER_ID WHERE sh.SHIPMENT_TYPE = ''Outbound'' AND sh.STATUS IN (''Delivered'',''Closed'') GROUP BY c.REVENUE_TIER ORDER BY OTD_PCT DESC'
        )
    );

-- ============================================================
-- PROCUREMENT_INVENTORY_FINANCE_SV - Working capital analysis
-- ============================================================
CREATE OR REPLACE SEMANTIC VIEW PROCUREMENT_INVENTORY_FINANCE_SV
    TABLES (
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_SUPPLIER UNIQUE (SUPPLIER_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PART UNIQUE (PART_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_PLANT UNIQUE (PLANT_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_PURCHASE_ORDER UNIQUE (PO_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_INVENTORY UNIQUE (INVENTORY_ID)
    )
    RELATIONSHIPS (
        PO_TO_PLANT AS FACT_PURCHASE_ORDER(PLANT_ID) REFERENCES DIM_PLANT(PLANT_ID),
        PO_TO_SUPPLIER AS FACT_PURCHASE_ORDER(SUPPLIER_ID) REFERENCES DIM_SUPPLIER(SUPPLIER_ID),
        INVENTORY_TO_PART AS FACT_INVENTORY(PART_ID) REFERENCES DIM_PART(PART_ID),
        INVENTORY_TO_PLANT AS FACT_INVENTORY(PLANT_ID) REFERENCES DIM_PLANT(PLANT_ID)
    )
    FACTS (
        FACT_PURCHASE_ORDER.TOTAL_VALUE AS TOTAL_VALUE,
        FACT_INVENTORY.TOTAL_VALUE AS TOTAL_VALUE,
        FACT_INVENTORY.DAYS_OF_INVENTORY AS DAYS_OF_INVENTORY
    )
    DIMENSIONS (
        DIM_SUPPLIER.SUPPLIER_ID AS SUPPLIER_ID,
        DIM_SUPPLIER.SUPPLIER_NAME AS SUPPLIER_NAME,
        DIM_PART.PART_ID AS PART_ID,
        DIM_PART.PART_NAME AS PART_NAME,
        DIM_PART.PART_FAMILY AS PART_FAMILY,
        DIM_PLANT.PLANT_ID AS PLANT_ID,
        DIM_PLANT.PLANT_NAME AS PLANT_NAME,
        FACT_PURCHASE_ORDER.PO_ID AS PO_ID,
        FACT_PURCHASE_ORDER.SUPPLIER_ID AS SUPPLIER_ID,
        FACT_PURCHASE_ORDER.PLANT_ID AS PLANT_ID,
        FACT_PURCHASE_ORDER.STATUS AS STATUS,
        FACT_PURCHASE_ORDER.ORDER_DATE AS ORDER_DATE,
        FACT_INVENTORY.INVENTORY_ID AS INVENTORY_ID,
        FACT_INVENTORY.PART_ID AS PART_ID,
        FACT_INVENTORY.PLANT_ID AS PLANT_ID
    )
    COMMENT = 'Cross-domain working capital: links procurement spend to inventory positions for financial analysis.'
    AI_VERIFIED_QUERIES (
        "Working capital in inventory" AS (
            QUESTION 'What is the total working capital tied up in inventory?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT SUM(TOTAL_VALUE) AS WORKING_CAPITAL_IN_INVENTORY FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_INVENTORY'
        )
    );

-- ============================================================
-- SUPPLIER_SHIPMENT_WAREHOUSE_SV - Inbound logistics
-- ============================================================
CREATE OR REPLACE SEMANTIC VIEW SUPPLIER_SHIPMENT_WAREHOUSE_SV
    TABLES (
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_SUPPLIER UNIQUE (SUPPLIER_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_CARRIER UNIQUE (CARRIER_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_WAREHOUSE UNIQUE (WAREHOUSE_ID),
        AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SHIPMENT UNIQUE (SHIPMENT_ID)
    )
    RELATIONSHIPS (
        SHIPMENT_TO_CARRIER AS FACT_SHIPMENT(CARRIER_ID) REFERENCES DIM_CARRIER(CARRIER_ID),
        SHIPMENT_TO_SUPPLIER AS FACT_SHIPMENT(SUPPLIER_ID) REFERENCES DIM_SUPPLIER(SUPPLIER_ID)
    )
    FACTS (
        DIM_SUPPLIER.DELIVERY_SCORE AS DELIVERY_SCORE,
        DIM_CARRIER.ON_TIME_RATE AS ON_TIME_RATE,
        FACT_SHIPMENT.FREIGHT_COST AS FREIGHT_COST,
        FACT_SHIPMENT.WEIGHT_KG AS WEIGHT_KG
    )
    DIMENSIONS (
        DIM_SUPPLIER.SUPPLIER_ID AS SUPPLIER_ID,
        DIM_SUPPLIER.SUPPLIER_NAME AS SUPPLIER_NAME,
        DIM_SUPPLIER.TIER_LEVEL AS TIER_LEVEL,
        DIM_SUPPLIER.COUNTRY AS COUNTRY,
        DIM_SUPPLIER.REGION AS REGION,
        DIM_CARRIER.CARRIER_ID AS CARRIER_ID,
        DIM_CARRIER.CARRIER_NAME AS CARRIER_NAME,
        DIM_CARRIER.SERVICE_TYPE AS SERVICE_TYPE,
        DIM_WAREHOUSE.WAREHOUSE_ID AS WAREHOUSE_ID,
        DIM_WAREHOUSE.WAREHOUSE_NAME AS WAREHOUSE_NAME,
        DIM_WAREHOUSE.WAREHOUSE_TYPE AS WAREHOUSE_TYPE,
        DIM_WAREHOUSE.PLANT_ID AS PLANT_ID,
        FACT_SHIPMENT.SHIPMENT_ID AS SHIPMENT_ID,
        FACT_SHIPMENT.SHIPMENT_TYPE AS SHIPMENT_TYPE,
        FACT_SHIPMENT.SUPPLIER_ID AS SUPPLIER_ID,
        FACT_SHIPMENT.CARRIER_ID AS CARRIER_ID,
        FACT_SHIPMENT.DESTINATION_PLANT_ID AS DESTINATION_PLANT_ID,
        FACT_SHIPMENT.STATUS AS STATUS,
        FACT_SHIPMENT.IS_ON_TIME AS IS_ON_TIME,
        FACT_SHIPMENT.SHIP_DATE AS SHIP_DATE,
        FACT_SHIPMENT.PROMISED_DELIVERY_DATE AS PROMISED_DELIVERY_DATE,
        FACT_SHIPMENT.ACTUAL_DELIVERY_DATE AS ACTUAL_DELIVERY_DATE
    )
    COMMENT = 'Cross-domain view: Suppliers to shipments to warehouses for end-to-end inbound logistics, transit analysis, and receiving performance.'
    AI_VERIFIED_QUERIES (
        "Inbound shipment OTD by supplier" AS (
            QUESTION 'What is the on-time delivery rate for inbound shipments by supplier?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT s.SUPPLIER_NAME, COUNT(CASE WHEN sh.IS_ON_TIME THEN 1 END)*100.0/NULLIF(COUNT(*),0) AS OTD_PCT FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SHIPMENT sh JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_SUPPLIER s ON sh.SUPPLIER_ID = s.SUPPLIER_ID WHERE sh.SHIPMENT_TYPE = ''Inbound'' AND sh.STATUS IN (''Delivered'',''Closed'') GROUP BY s.SUPPLIER_NAME ORDER BY OTD_PCT LIMIT 10'
        ),
        "Freight cost by carrier" AS (
            QUESTION 'What is total freight cost by carrier?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT c.CARRIER_NAME, SUM(sh.FREIGHT_COST) AS TOTAL_FREIGHT, COUNT(*) AS SHIPMENT_COUNT FROM AEROSPACE_SUPPLY_CHAIN_AI.RAW.FACT_SHIPMENT sh JOIN AEROSPACE_SUPPLY_CHAIN_AI.RAW.DIM_CARRIER c ON sh.CARRIER_ID = c.CARRIER_ID GROUP BY c.CARRIER_NAME ORDER BY TOTAL_FREIGHT DESC'
        )
    );

-- ============================================================
-- EXECUTIVE_SUMMARY_SV - Monthly KPI dashboard
-- ============================================================
CREATE OR REPLACE SEMANTIC VIEW EXECUTIVE_SUMMARY_SV
    TABLES (
        AEROSPACE_SUPPLY_CHAIN_AI.ANALYTICS.EXECUTIVE_KPI_MONTHLY
    )
    FACTS (
        EXECUTIVE_KPI_MONTHLY.OTD_PCT AS OTD_PCT,
        EXECUTIVE_KPI_MONTHLY.FILL_RATE_PCT AS FILL_RATE_PCT,
        EXECUTIVE_KPI_MONTHLY.PROCUREMENT_SPEND AS PROCUREMENT_SPEND,
        EXECUTIVE_KPI_MONTHLY.AVG_YIELD_RATE AS AVG_YIELD_RATE,
        EXECUTIVE_KPI_MONTHLY.SCRAP_RATE AS SCRAP_RATE,
        EXECUTIVE_KPI_MONTHLY.DEFECT_RATE AS DEFECT_RATE,
        EXECUTIVE_KPI_MONTHLY.TOTAL_COPQ AS TOTAL_COPQ,
        EXECUTIVE_KPI_MONTHLY.TOTAL_SHIPMENTS AS TOTAL_SHIPMENTS,
        EXECUTIVE_KPI_MONTHLY.TOTAL_REVENUE AS TOTAL_REVENUE,
        EXECUTIVE_KPI_MONTHLY.PO_COUNT AS PO_COUNT,
        EXECUTIVE_KPI_MONTHLY.WO_COUNT AS WO_COUNT,
        EXECUTIVE_KPI_MONTHLY.QUALITY_EVENT_COUNT AS QUALITY_EVENT_COUNT
    )
    DIMENSIONS (
        EXECUTIVE_KPI_MONTHLY.YEAR AS YEAR,
        EXECUTIVE_KPI_MONTHLY.MONTH_NAME AS MONTH_NAME,
        EXECUTIVE_KPI_MONTHLY.QUARTER AS QUARTER,
        EXECUTIVE_KPI_MONTHLY.FISCAL_YEAR AS FISCAL_YEAR,
        EXECUTIVE_KPI_MONTHLY.FISCAL_QUARTER AS FISCAL_QUARTER,
        EXECUTIVE_KPI_MONTHLY.MONTH AS MONTH
    )
    COMMENT = 'Executive KPI dashboard: pre-aggregated monthly metrics across all supply chain domains for leadership reporting.'
    AI_VERIFIED_QUERIES (
        "Monthly KPI dashboard" AS (
            QUESTION 'Show me the monthly KPI dashboard for this year'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT MONTH_NAME, OTD_PCT, FILL_RATE_PCT, AVG_YIELD_RATE, SCRAP_RATE, DEFECT_RATE, PROCUREMENT_SPEND, TOTAL_REVENUE FROM AEROSPACE_SUPPLY_CHAIN_AI.ANALYTICS.EXECUTIVE_KPI_MONTHLY WHERE YEAR = 2026 ORDER BY MONTH'
        ),
        "Quarterly trend" AS (
            QUESTION 'How are our KPIs trending by quarter?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT QUARTER, ROUND(AVG(OTD_PCT),1) AS AVG_OTD, ROUND(AVG(FILL_RATE_PCT),1) AS AVG_FILL_RATE, ROUND(AVG(AVG_YIELD_RATE),1) AS AVG_YIELD, SUM(PROCUREMENT_SPEND) AS TOTAL_SPEND FROM AEROSPACE_SUPPLY_CHAIN_AI.ANALYTICS.EXECUTIVE_KPI_MONTHLY WHERE YEAR = 2026 GROUP BY QUARTER ORDER BY QUARTER'
        ),
        "Metrics vs targets" AS (
            QUESTION 'How do our current metrics compare to targets?'
            ONBOARDING_QUESTION FALSE
            SQL 'SELECT MONTH_NAME, OTD_PCT AS OTD_ACTUAL, 95 AS OTD_TARGET, FILL_RATE_PCT AS FILL_ACTUAL, 98 AS FILL_TARGET, AVG_YIELD_RATE AS YIELD_ACTUAL, 97 AS YIELD_TARGET FROM AEROSPACE_SUPPLY_CHAIN_AI.ANALYTICS.EXECUTIVE_KPI_MONTHLY WHERE YEAR = 2026 ORDER BY MONTH'
        )
    );
